#pragma once

#define ACTOR_DROP_COIN				255

enum ACTOR_SORT_
{
	ACTOR_SORT_NONE,
	ACTOR_SORT_USER,
	ACTOR_SORT_MOB,
	XXX_ACTOR_SORT_NPC,
	ACTOR_SORT_ITEM,
	XXX_ACTOR_SORT_PARTY,
	XXX_ACTOR_SORT_PADDLER,
	XXX_ACTOR_SORT_EVENT,
	XXX_ACTOR_SORT_REGEN,			// 자동 회복시 actor_info에서 쓴다.
	XXX_ACTOR_SORT_GUILD,
	ACTOR_SORT_SELF_SHOP,			// 개인상점 개설중 - Map 정보 보낼 때에만 사용한다.
};

enum ACTOR_STATE_
{
	ACTOR_STATE_NONE = 0,
	ACTOR_STATE_MOVE,
	ACTOR_STATE_DEAD,
	ACTOR_STATE_MAX
};

// 이동 상태
enum ACTOR_MOVESTATE_
{
	ACTOR_MOVESTATE_ERROR = 0,
	ACTOR_MOVESTATE_STOP,
	ACTOR_MOVESTATE_PORTAL,
	ACTOR_MOVESTATE_REGIONMOVE,
};

// 이동 동작
enum ACTOR_MOVEFLAGS
{
	ACTOR_MOVEFLAG_NONE = 0x0000,		// 동작 없음
	ACTOR_MOVEFLAG_WALK = 0x0001,		// 걷기
	ACTOR_MOVEFLAG_RUN = 0x0002,		// 달리기
	ACTOR_MOVEFLAG_JUMP = 0x0004,		// 점프
	ACTOR_MOVEFLAG_JUMPSTOP = 0x0008,		// 착지
	ACTOR_MOVEFLAG_RUN_ATTACK = 0x0080,		// 공격좌표로 0.3초내로 뛰어가기
	ACTOR_MOVEFLAG_KNOCKBACK = 0x0010,		// 넉백 이동
};

// 삭제 타입
enum ACTOR_DELETE_TYPE
{
	ACTOR_DELETE_TYPE_NONE,						// 활성화 상태
	ACTOR_DELETE_TYPE_TEMP,						// 임시 삭제
	ACTOR_DELETE_TYPE_TRANSMIGRATE_SERVER,		// 서버 이전 상태
	ACTOR_DELETE_TYPE_COMPLETED,				// 완전 삭제
};

// 삭제 DB flag value
enum ACTOR_DELETE_FLAG_VALUE
{
	ACTOR_DELETE_FLAG_VALUE_DELETE_WAIT = 1 << 0,			// 비활성 상태
	ACTOR_DELETE_FLAG_VALUE_CHANE_NAME = 1 << 2,			// 이름변경 신청 상태
	ACTOR_DELETE_FLAG_VALUE_BOOST_EVENT = 1 << 3,			// 부스터 서버 이전 상태
	ACTOR_DELETE_FLAG_VALUE_DELETED = 999,					// 활성화 상태 (1111100111)
	ACTOR_DELETE_FLAG_VALUE_COMBINE_DELETED = 1000,			// 통합 캐릭터 삭제 (1111101000)
};
