#pragma once

enum PTYPE_GUILD_
{
	PTYPE_GUILD_ENTRY = 0,					//  0
	PTYPE_GUILD_CREATE,						// 문파 생성
	PTYPE_GUILD_UPGRADE,					// 문파 승급
	PTYPE_GUILD_DESTROY,					// 문파 해체
	PTYPE_GUILD_SECEDE,						// 문원 탈퇴
	PTYPE_GUILD_PURGE,						// 문원 추방
	PTYPE_GUILD_NOTIFY_MESSAGE,				// 문파 공지
	PTYPE_GUILD_PROMOTION_USER,				// 문원의 승급
	PTYPE_GUILD_OPEN_CLOSE_KEEP,			// 문파 창고 사용
	PTYPE_GUILD_KEEP_DATA,					// 문파 창고 사용 종료
	PTYPE_GUILD_CHANGE_MARK,				// 문파 문장 변경
	PTYPE_GUILD_MEMBER_CHARGE_COIN,			// 개인에게 분배된 세금을 준다.
	PTYPE_GUILD_CHARGE_COIN,				// 세율로 거둔 세금을 문파에 적용
	PTYPE_GUILD_REGISTER_MARK,				// 문파 문장(사용자) 등록

	PTYPE_GUILD_INMAP_LOCAL,				// 유저가 맵에 들어오는 정보, only local
	PTYPE_GUILD_OUTMAP_LOCAL,				// 유저가 맵에 나가는 정보, only local
	PTYPE_GUILD_CHANGE_LEVEL_LOCAL,			// 유저의 레벨 변경, only local
	PTYPE_GUILD_ADD_MEMBER_LOCAL,			// 문원으로 가입
	PTYPE_GUILD_DELETE_CHARACTER_LOCAL,		// 캐릭터 삭제시 처리

	PTYPE_GUILD_MY_POSITION_INFO,			// gcontianer가 가지고 있는 guild position 정보 갱신
	PTYPE_GUILD_INFO,						// 문파정보
	PTYPE_GUILD_MEMBER_INFO_ALL,			// 문원 정보
	PTYPE_GUILD_MEMBER_INFO_ONE_ANNOUNCE,	// 문원 정보
	PTYPE_GUILD_MEMBER_LOGINON_ANNOUNCE,			// 문원 logon 정보
	PTYPE_GUILD_MEMBER_LOGINOFF_ANNOUNCE,			// 문원 logoff 정보
	PTYPE_GUILD_CHANGE_POSITION_ANNOUNCE,			// 문원의 변경된 정보
	PTYPE_GUILD_CHANGE_LEVEL_ANNOUNCE,				// 문원의 변경된 레벨
	PTYPE_GUILD_CHANGE_SORT_ANNOUNCE,				// 문파 sort 변경
	PTYPE_GUILD_CHANGE_MARK_ANNOUNCE,				// 문파 문장 변경
	PTYPE_GUILD_CHANGE_NOTIFY_MESSAGE_ANNOUNCE,		// 문파 공지 변경
	PTYPE_GUILD_CHANGE_MAKE_BATTLE_PURIFY_GUILD_ITEM_ANNOUNCE,		// 문파 자산의 변경

	PTYPE_GUILD_DESTROY_ANNOUNCE,			// 문파 해체 broadcasting
	PTYPE_GUILD_SECEDE_MEMBER_ANNOUNCE,		// 문원 탈퇴 broadcasting
	PTYPE_GUILD_PURGE_MEMBER_ANNOUNCE,		// 문원 추방 broadcasting

	// for siege
	XXX_PTYPE_GUILD_SIEGE_UPDATE_NEXT_TAX_RATE,
	XXX_PTYPE_GUILD_SIEGE_UPDATE_INCOME_RATE,

	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_INFO,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_SIEGE_TIME,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_INVEST_GRADE,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_DEVELOPE,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_TAX,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_FLAG_ID,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_SIEGE_STATE,
	XXX_PTYPE_GUILD_SIEGE_CASTLE_DC_GATE_OPEN,
	XXX_PTYPE_GUILD_SIEGE_DECLARE_INFO,

	XXX_PTYPE_GUILD_SIEGE_APPLY_NEXT_TAX_LOCAL,
	XXX_PTYPE_GUILD_SIEGE_APPLY_AUTO_MINUS_DEVELOPE_LOCAL,
	XXX_PTYPE_GUILD_SIEGE_END_LOCAL,
	XXX_PTYPE_GUILD_SIEGE_OCCPUY_CASTLE,


	XXX_PTYPE_GUILD_SIEGE_CHANGE_INCOME_RATE,
	XXX_PTYPE_GUILD_SIEGE_DECLARE,
	XXX_PTYPE_GUILD_SIEGE_SET_NEXT_TAX_RATE,
	XXX_PTYPE_GUILD_SIEGE_DEVELOP,
	XXX_PTYPE_GUILD_SIEGE_INVEST,
	XXX_PTYPE_GUILD_SIEGE_OPEN_GATE,
	XXX_PTYPE_GUILD_SIEGE_CLOSE_GATE,
	XXX_PTYPE_GUILD_SIEGE_CHANGE_SIEGE_STATUS,

	XXX_PTYPE_GUILD_SIEGE_EMPLOY_DEFENCE_MOB,

	XXX_PTYPE_GUILD_SIEGE_CLEAR_DECLARE_LIST,
	XXX_PTYPE_GUILD_SIEGE_OCCUPY_CASTLE,
	XXX_PTYPE_GUILD_SIEGE_REPAIR_GATE,

	PTYPE_GUILD_BUY_GUILD_ITEM,

	XXX_PTYPE_GUILD_SIEGE_BATTLE_WINNER,

	PTYPE_GUILD_UPDATE_MAKE_GUILD_ITEM,
	PTYPE_GUILD_UPDATE_BATTLE_GUILD_ITEM,
	PTYPE_GUILD_UPDATE_PURIFY_GUILD_ITEM,
	PTYPE_GUILD_SET_MAKE_GUILD_ITEM,
	PTYPE_GUILD_SET_BATTLE_GUILD_ITEM,
	PTYPE_GUILD_SET_PURIFY_GUILD_ITEM,
	PTYPE_GUILD_SET_RICHES_GUILD_ITEM,

	PTYPE_GUILD_KEEP_LINES,					// 길드 창고 라인수
	PTYPE_GUILD_KEEP_LINES_ANNOUNCE,		// 길드 창고 라인수 (변경시 모든 길드원에게 전송)
	PTYPE_GUILD_KEEP_UPDATE_ITEM,			// 길드 창고 아이템의 변동을 처리

	PTYPE_GUILD_RESET_GUILD_INFO,			// 정보 보정

	PTYPE_GUILD_TOURNAMENT_OPEN_REQ,
	PTYPE_GUILD_TOURNAMENT_INFO,
	PTYPE_GUILD_TOURNAMENT_STATUS,
	PTYPE_GUILD_TOURNAMENT_REGISTER_REQ,
	PTYPE_GUILD_TOURNAMENT_REGISTER_RES,
	PTYPE_GUILD_TOURNAMENT_REG_COUNT,
	PTYPE_GUILD_TOURNAMENT_NEXT_STATUS,
	PTYPE_GUILD_TOURNAMENT_UNREGISTER_REQ,
	PTYPE_GUILD_TOURNAMENT_UNREGISTER_RES,
	PTYPE_GUILD_TOURNAMENT_REGISTER_ANNOUNCE,
	PTYPE_GUILD_TOURNAMENT_UNREGISTER_ANNOUNCE,
	PTYPE_GUILD_TOURNAMENT_JOINMAP_REQ,
	PTYPE_GUILD_TOURNAMENT_JOINMAP_RES,
	PTYPE_GUILD_TOURNAMENT_QUEUEMAP_REQ,
	PTYPE_GUILD_TOURNAMENT_QUEUEMAP_RES,
	PTYPE_GUILD_TOURNAMENT_GUILD_LIST,
	PTYPE_GUILD_TOURNAMENT_MATCH_LIST,
	PTYPE_GUILD_TOURNAMENT_CREATE_MATCH_MAP,
	PTYPE_GUILD_TOURNAMENT_START_MATCH,
	PTYPE_GUILD_TOURNAMENT_END_GAME,
	PTYPE_GUILD_TOURNAMENT_END,
	PTYPE_GUILD_TOURNAMENT_UNBIND_TIME,
	PTYPE_GUILD_TOURNAMENT_REWARD,
	PTYPE_GUILD_TOURNAMENT_REWARD_SECOND,
	PTYPE_GUILD_TOURNAMENT_WINNER_LIST,
	PTYPE_GUILD_TOURNAMENT_GUILD_USER_COUNT,
	PTYPE_GUILD_TOURNAMENT_REWARD_INFO,

	PTYPE_GUILD_TIMER,
	PTYPE_GUILD_ADD_GUILD_AFFECT,
	PTYPE_GUILD_REMOVE_GUILD_AFFECT,
	PTYPE_GUILD_AFFECT,
	PTYPE_GUILD_CHANGE_GUILD_NAME,
	PTYPE_GUILD_CHANGE_GUILD_NAME_RES,
	PTYPE_GUILD_CHANGE_GUILD_NAME_ANNOUNCE,

	PTYPE_GUILD_GUILD_MASTER_MANDATE,		// 길드장 위임
	PTYPE_GUILD_LEVEL_UP_GM_COMMAND,		// GM명령어로 길드의 등급을 상향시킴 (절대 하향없음)
	PTYPE_GUILD_DESTROY_GUILD_GM_COMMAND,	// GM명령어로 길드 해산

	PTYPE_GUILD_GUILD_WAR_REQUEST,						// [길드전쟁] 선포
	PTYPE_GUILD_GUILD_WAR_ACCEPT,						// [길드전쟁] 수락
	PTYPE_GUILD_GUILD_WAR_GIVEUP,						// [길드전쟁] 항복
	PTYPE_GUILD_GUILD_WAR_OTHER_GUILD_INFO,				// [길드전쟁] 클라이언트가 맵인시 매번 보내주는 길드전쟁 관련 정보
	PTYPE_GUILD_GUILD_WAR_OTHER_GUILD_INFO_ANNOUNCE,	// [길드전쟁] 클라이언트가 맵인시 매번 보내주는 길드전쟁 관련 정보

	PTYPE_GUILD_REGION_WAR_INFO,
	PTYPE_GUILD_START_REGION_WAR,
	PTYPE_GUILD_END_REGION_WAR,
	PTYPE_GUILD_ADD_CURSE_AMULET,
	PTYPE_GUILD_ADD_BLESSING_AMULET,
	PTYPE_GUILD_COLLECT_TAX,
	PTYPE_GUILD_ADJUST_INCOME_TAX_RATE_REQ,
	PTYPE_GUILD_ADJUST_INCOME_TAX_RATE_RES,
	PTYPE_GUILD_ADJUST_EXCISE_TAX_RATE_REQ,
	PTYPE_GUILD_ADJUST_EXCISE_TAX_RATE_RES,
	PTYPE_GUILD_WITHDRAW_REQ,
	PTYPE_GUILD_WITHDRAW_RES,
	PTYPE_GUILD_CANCEL_WITHDRAW,
	PTYPE_GUILD_CAPTURE_REGION,
	PTYPE_GUILD_ADD_WAR_GUILD_REQ,
	PTYPE_GUILD_ADD_WAR_GUILD_RES,
	PTYPE_GUILD_REMOVE_WAR_GUILD_REQ,
	PTYPE_GUILD_REMOVE_WAR_GUILD_RES,
	PTYPE_GUILD_ADD_WAR_GUILD_ANNOUNCE,
	PTYPE_GUILD_REMOVE_WAR_GUILD_ANNOUNCE,
	PTYPE_GUILD_START_REGION_WAR_REQ,
	PTYPE_GUILD_END_REGION_WAR_REQ,
	PTYPE_GUILD_REGION_WAR_ALL_CITY_INFO,
	PTYPE_IN_MAP_GUILD,
	PTYPE_GUILD_REGION_WAR_LOG,
	PTYPE_GUILD_REGION_WAR_CHECK_FAME_REQ,
	PTYPE_GUILD_REGION_WAR_CHECK_FAME_RES,
	PTYPE_GUILD_REGION_WAR_INC_FAME,
	PTYPE_GUILD_CHANGE_ACTOR_NAME,

	PTYPE_GUILD_DONATE_RICHES_GUILD_ITEM_REQ,
	PTYPE_GUILD_DONATE_RICHES_GUILD_ITEM_RES,
	PTYPE_GUILD_UPDATE_RICHES_GUILD_ITEM,
	PTYPE_GUILD_CANCEL_DONATE_RICHES_GUILD_ITEM_REQ,
	PTYPE_GUILD_START_RESEARCH_REQ,
	PTYPE_GUILD_START_RESEARCH_RES,
	PTYPE_GUILD_CANCEL_RESEARCH_REQ,
	PTYPE_GUILD_CANCEL_RESEARCH_RES,
	PTYPE_GUILD_USE_RESEARCH_REQ,
	PTYPE_GUILD_USE_RESEARCH_RES,
	PTYPE_GUILD_COMPLETE_RESEARCH_REQ,
	PTYPE_GUILD_COMPLETE_RESEARCH_RES,
	PTYPE_GUILD_TIME_RESEARCH_REQ,
	PTYPE_GUILD_TIME_RESEARCH_RES,
	PTYPE_GUILD_DELETE_RESEARCH_REQ,
	PTYPE_GUILD_DELETE_RESEARCH_RES,
	PTYPE_GUILD_RESEARCH_INFO_ANNOUNCE,
	PTYPE_GUILD_RESEARCH_ALL_INFO_ANNOUNCE,

	PTYPE_GUILD_MAX							// MAX
};

enum PTYPE_PARTY_
{
	PTYPE_PARTY_CREATE_LOCAL,
	PTYPE_PARTY_ADD_MEMBER_LOCAL,
	PTYPE_PARTY_SECEDE_MEMBER,
	PTYPE_PARTY_PURGE_MEMEBER,
	PTYPE_PARTY_CHANGE_MASTER,
	PTYPE_PARTY_CHANGE_HP_MP_SP,
	PTYPE_PARTY_CHANGE_LIVE,
	PTYPE_PARTY_CHANGE_DEAD,
	PTYPE_PARTY_CHANGE_AUTO_DEVIDE,

	PTYPE_PARTY_CHANGE_LEVEL_LOCAL,
	PTYPE_PARTY_IN_MAP_LOCAL,
	PTYPE_PARTY_OUT_MAP_LOCAL,

	PTYPE_PARTY_INFO,
	PTYPE_PARTY_MEMBER_INFO_ONE_ANNOUNCE,
	PTYPE_PARTY_SECEDE_MEMBER_ANNOUNCE,
	PTYPE_PARTY_PURGE_MEMBER_ANNOUNCE,
	PTYPE_PARTY_CHANGE_MASTER_ANNOUNCE,
	PTYPE_PARTY_CHANGE_HP_MP_SP_ANNOUNCE,
	PTYPE_PARTY_CHANGE_LIVE_ANNOUNCE,
	PTYPE_PARTY_CHANGE_DEAD_ANNOUNCE,
	PTYPE_PARTY_CHANGE_AUTO_DEVIDE_ANNOUNCE,
	PTYPE_PARTY_CHANGE_MAP_ANNOUNCE,
	PTYPE_PARTY_CHANGE_LEVEL_ANNOUNCE,

	PTYPE_PARTY_ANNOUNCE_HPSPMP,
	PTYPE_PARTY_LOADED,
	PTYPE_PARTY_DESTROY_PARTY,

	PTYPE_PARTY_CHAT_UPDATE_PARTY_ID,

	PTYPE_PARTY_IN_MAP_LOCAL_FROM_DCONTAINERBROKER,				// 맵인 정보를 dcontainerbroker에서 보내줌

	PTYPE_PARTY_AGENCY_REGISTER_REQ,
	PTYPE_PARTY_AGENCY_REGISTER_RES,
	PTYPE_PARTY_AGENCY_UNREGISTER_REQ,
	PTYPE_PARTY_AGENCY_UNREGISTER_RES,
	PTYPE_PARTY_AGENCY_SOLO_LIST_REQ,
	PTYPE_PARTY_AGENCY_SOLO_LIST_RES,
	PTYPE_PARTY_AGENCY_PARTY_LIST_REQ,
	PTYPE_PARTY_AGENCY_PARTY_LIST_RES,
	PTYPE_PARTY_AGENCY_PARTY_INFO_REQ,
	PTYPE_PARTY_AGENCY_PARTY_INFO_RES,
	PTYPE_PARTY_AGENCY_REQUEST_PARTY_INVITE_REQ,
	PTYPE_PARTY_AGENCY_REQUEST_PARTY_INVITE_RES,
	PTYPE_PARTY_AGENCY_REQUEST_PARTY_INVITE_ANNOUNCE,
	PTYPE_PARTY_AGENCY_ANNOUNCE_MESSAGE_REQ,
	PTYPE_PARTY_AGENCY_ANNOUNCE_MESSAGE_RES,
	PTYPE_PARTY_AGENCY_CHANGE_COMMENT_REQ,
	PTYPE_PARTY_AGENCY_CHANGE_COMMENT_RES,
	PTYPE_PARTY_CHANGE_ACTOR_NAME,
	PTYPE_PARTY_CHANGE_COIN_DEVIDE,
	PTYPE_PARTY_CHANGE_COIN_DEVIDE_ANNOUNCE,
};

enum PTYPE_MAIL_
{
	PTYPE_MAIL_SEND,
	PTYPE_MAIL_LIST,
	PTYPE_MAIL_READ,
	PTYPE_MAIL_PICKUP_ITEM,
	PTYPE_MAIL_DELETE,
	PTYPE_MAIL_DELETE_ACTOR,
	PTYPE_MAIL_SEND_SYSTEM_MAIL,

	PTYPE_MAIL_SEND_ANNOUNCE,
};

enum PTYPE_CONSIGN_
{
	PTYPE_CONSIGN_ITEM_LIST,
	PTYPE_CONSIGN_REGIST_ITEM_LIST,
	PTYPE_CONSIGN_REGIST_ITEM,
	PTYPE_CONSIGN_RECALL_ITEM,
	PTYPE_CONSIGN_BUY_ITEM,
	PTYPE_CONSIGN_CALCULATE_LIST,
	PTYPE_CONSIGN_CALCULATE,
	PTYPE_CONSIGN_SELL_ALERT,
	PTYPE_CONSIGN_INMAP,
	PTYPE_CONSIGN_CHANGE_ACTOR_NAME,
};

enum PTYPE_CBROKER_
{
	PTYPE_CBROKER_IN_MAP_REQ,
	PTYPE_CBROKER_IN_MAP_RES,
	PTYPE_CBROKER_OUT_MAP,

	PTYPE_CBROKER_JOIN_MISSION_MAP_REQ,
	PTYPE_CBROKER_JOIN_MISSION_MAP_RES,

	PTYPE_CBROKER_OPEN_CLOSE_MISSION_MAP_REQ,

	PTYPE_CBROKER_JACKPOT_CLICK_REQ,		// 유저가 jackpot start를 눌렀을때
	PTYPE_CBROKER_JACKPOT_CLICK_RES,		// PTYPE_CBROKER_JACKPOT_CLICK_REQ에 대한 응답

	PTYPE_CBROKER_JACKPOT_FROM_MOB_COIN,	// 몹이 죽으면서 dodb로 보내는 패킷

	PTYPE_CBROKER_ADD_ACCEPT_FRIEND,				// 친구 목록 추가
	PTYPE_CBROKER_ADD_DENY_FRIEND,					// 거부 목록 추가
	PTYPE_CBROKER_DELETE_ACCEPT_FRIEND,				// 친구 목록 삭제
	PTYPE_CBROKER_DELETE_DENY_FRIEND,				// 거부 목록 삭제
	PTYPE_CBROKER_ADD_ACCEPT_FRIEND_REQUEST_ANSWER,	// 친구 추가 요청
	PTYPE_CBROKER_ACCEPT_FRIEND_LOGONOFF,			// 친구 loginout

	PTYPE_CBROKER_CHANGE_USER_LEVEL,				// 유저의 레벨이 변화함

	PTYPE_CBROKER_GUILD_INVITE_USER,				// 문원 초대
	PTYPE_CBROKER_GUILD_INVITE_USER_ANSWER,			// 문원 초대 응답

	PTYPE_CBROKER_PARTY_INVITE_USER,				// 파티 초대
	PTYPE_CBROKER_PARTY_INVITE_USER_ANSWER,			// 파티 초대 응답

	PTYPE_CBROKER_CHANGE_GUILD_POSITION_LOCAL,		// only local
	PTYPE_CBROKER_DELETE_CHARACTER_LOCAL,			// only local

	PTYPE_CBROKER_PARTY_ID_LOCAL,					// only local (party thread -> duser thread)

	PTYPE_CBROKER_INVITE_GUILD_TIMEOUT_LOCAL,		// 문파 초대시 시간 초과
	PTYPE_CBROKER_INVITE_PARTY_TIMEOUT_LOCAL,		// 무리 초대시 시간 초과

	PTYPE_CBROKER_INVITE_FRIEND_TIMEOUT_LOCAL,		// 친구 초대시 시간 초과
	XXX_PTYPE_CBROKER_SIEGE_JOIN_MAP_RES,

	PTYPE_CBROKER_CALL_PLAYER_REQ,
	PTYPE_CBROKER_CALL_PLAYER_RES,

	PTYPE_CBROKER_MOVE_TO_PLAYER_REQ,
	PTYPE_CBROKER_MOVE_TO_PLAYER_RES,

	PTYPE_CBROKER_USER_KEEP_INFO,					// 유저가 사용하는 창고 정보

	PTYPE_CBROKER_USER_KEEP_LINES,					// 유저가 사용하는 창고 정보, 라인 변경
	PTYPE_CBROKER_USER_KEEP_COIN,					// 유저가 사용하는 창고 정보, 코인 변경
	PTYPE_CBROKER_USER_KEEP_ADD_ITEM,				// 유저가 사용하는 창고 정보, 아이템 추가
	PTYPE_CBROKER_USER_COMBINE_KEEP_ADD_ITEM,
	PTYPE_CBROKER_USER_KEEP_REMOVE_ITEM,			// 유저가 사용하는 창고 정보, 아이템 제거
	PTYPE_CBROKER_USER_COMBINE_KEEP_REMOVE_ITEM,
	PTYPE_CBROKER_USER_KEEP_UPDATE_ITEM_COUNT,		// 유저가 사용하는 창고 정보, 아이템 카운트 변경
	PTYPE_CBROKER_USER_KEEP_SWAP_ITEM,				// 유저가 사용하는 창고 정보, 아이템 위치 교환
	PTYPE_CBROKER_USER_KEEP_ALL_ITEM,				// 유저가 사용하는 창고 정보, 전체 업데이트
	PTYPE_CBROKER_SEND_MAIL_ALERT,
	PTYPE_CBROKER_WORLD_EVENT_STATUS,
	PTYPE_CBROKER_WORLD_EVENT_DEBUFF_QUEST_STATUS,
	PTYPE_CBROKER_ANNOUNCE_WORLD_EVENT,
	PTYPE_CBROKER_START_WORLD_EVENT,
	PTYPE_CBROKER_COMPLETE_WORLD_EVENT,
	PTYPE_CBROKER_WORLD_EVENT_COMPELTED_QUEST,
	PTYPE_CBROKER_WORLD_EVENT_KILLED_MOB,
	PTYPE_CBROKER_WORLD_EVENT_DEBUFF_COMPELTED_QUEST,
	PTYPE_CBROKER_START_WORLD_EVENT_REQ,
	PTYPE_CBROKER_NEXT_WORLD_EVENT_REQ,
	PTYPE_CBROKER_CLEAR_WORLD_EVENT_REQ,
	PTYPE_CBROKER_EDIT_WORLD_EVENT_REQ,
	PTYPE_CBROKER_EDIT_DEBUFF_QUEST_REQ,
	PTYPE_CBROKER_QUERY_PLAYER_POSITION_REQ,
	PTYPE_CBROKER_QUERY_PLAYER_POSITION_RES,
	PTYPE_CBROKER_CONSIGN_SELL_ALERT,
	PTYPE_CBROKER_WORLD_EVENT_TIMER,

	PTYPE_CBROKER_ACCEPT_FRIEND_INFO,				// 친구 목록 리스트
	PTYPE_CBROKER_ADD_FRIEND_INFO,					// 거부 목록 리스트
	PTYPE_CBROKER_TOWER_RANKING,
	PTYPE_CBROKER_RECORD_TOWER_RANKING,
	PTYPE_CBROKER_DROP_LIMIT_ITEM_REQ,
	PTYPE_CBROKER_DROP_LIMIT_ITEM_RES,
	PTYPE_CBROKER_OPEN_LIMIT_EVENT_ITEM_REQ,
	PTYPE_CBROKER_OPEN_LIMIT_EVENT_ITEM_RES,
	PTYPE_CBROKER_CREATE_LIMIT_UPDATE_TIMER,

	PTYPE_CBROKER_USER_COMBINE_KEEP_INFO,
	PTYPE_CBROKER_CHANGE_NAME_REQ,
	PTYPE_CBROKER_CHANGE_NAME_RES,
	PTYPE_CBROKER_CHANGE_NAME_ANNOUNCE,

	PTYPE_CBROKER_VOTE_EVENT_POLL_REQ,
	PTYPE_CBROKER_VOTE_EVENT_POLL_RES,
	PTYPE_CBROKER_EVENT_POLL_INFO_REQ,
	PTYPE_CBROKER_EVENT_POLL_INFO_RES,

	PTYPE_CBROKER_MISISON_TOURNAMENT_USER_SEED_INFO_REQ,
	PTYPE_CBROKER_MISISON_TOURNAMENT_USER_SEED_INFO,
	PTYPE_CBROKER_MISISON_TOURNAMENT_START,
	PTYPE_CBROKER_MISISON_TOURNAMENT_CLEAR,
	PTYPE_CBROKER_MISISON_TOURNAMENT_UPDATE_MATCH_USER,
	PTYPE_CBROKER_MISISON_TOURNAMENT_UPDATE_MATCH_LIST,
	PTYPE_CBROKER_MISISON_TOURNAMENT_REGISTER_SEED,
	PTYPE_CBROKER_MISISON_TOURNAMENT_UNREGISTER_SEED,
	PTYPE_CBROKER_MISISON_TOURNAMENT_SET_SEED,
	PTYPE_CBROKER_MISISON_TOURNAMENT_SEED_LIST_REQ,
	PTYPE_CBROKER_MISISON_TOURNAMENT_SEED_LIST_RES,

	PTYPE_CBROKER_MISISON_TOURNAMENT_MATCH_LIST_REQ,
	PTYPE_CBROKER_MISISON_TOURNAMENT_MATCH_LIST_RES,
	PTYPE_CBROKER_MISISON_TOURNAMENT_USER_RECORD_REQ,
	PTYPE_CBROKER_MISISON_TOURNAMENT_USER_RECORD_RES,
	PTYPE_CBROKER_MISISON_TOURNAMENT_RANKING_REQ,
	PTYPE_CBROKER_MISISON_TOURNAMENT_RANKING_RES,

	PTYPE_CBROKER_JACKPOT_GM_COMMAND,
	PTYPE_CBROKER_MISSIONMAP_POINT,

	PTYPE_CBROKER_LIMIT_EXCHANGE_DATA_REQ,						// 제한 교환 시스템 수량 요청
	PTYPE_CBROKER_LIMIT_EXCHANGE_DATA_RES,						// 제한 교환 시스템 수량 응답
	PTYPE_CBROKER_LIMIT_EXCHANGE_REQ,							// 제한 교환 시스템 교환 요청
	PTYPE_CBROKER_LIMIT_EXCHANGE_RES,							// 제한 교환 시스템 교환 요청 응답
	PTYPE_CBROKER_LIMIT_EXCHANGE_DATA_RES_INDEX,				// 제한 교환 시스템 특정 Index Update 정보 전달.
	PTYPE_CBROKER_LIMIT_EXCHANGE_CHANGE_COUNT_GM,				// 제한 교환 시스템 수량 변경 GM 패킷
	PTYPE_CBROKER_LIMIT_EXCHANGE_RESET,

	PTYPE_CBROKER_SCHEDULE_MAIL_REQ,
	PTYPE_CBROKER_SCHEDULE_MAIL_RES,
	PTYPE_CBROKER_SCHEDULE_MAIL_ON_OFF_REQ,

	PTYPE_CBROKER_LIMIT_ITEM_INFO_REQ,
	PTYPE_CBROKER_LIMIT_ITEM_INFO_RES,
	PTYPE_CBROKER_EDIT_LIMIT_ITEM_REQ,
	PTYPE_CBROKER_EDIT_LIMIT_ITEM_RES,

	PTYPE_CBROKER_MAX						// MAX
};

enum PTYPE_SOUL_CONSIGN_
{
	PTYPE_SOUL_CONSIGN_SEARCH,
	PTYPE_SOUL_CONSIGN_REGIST,
	PTYPE_SOUL_CONSIGN_REGIST_LIST,
	PTYPE_SOUL_CONSIGN_RECALL_ITEM,
	PTYPE_SOUL_CONSIGN_CALCULATE,
	PTYPE_SOUL_CONSIGN_BUY_ITEM,
	PTYPE_SOUL_CONSIGN_CHANGE_ACTOR_NAME,
};
