#pragma once

#define ATTACK_TARGET_COUNT_MAX		(20)

enum STATUS_FUNCTIONLINK_
{
	STATUS_FUNCTIONLINK_NONE = 0,
	STATUS_FUNCTIONLINK_ITEM,
	STATUS_FUNCTIONLINK_SKILL,
	STATUS_FUNCTIONLINK_ACTION,
	STATUS_FUNCTIONLINK_SOUL_ITEM,
	STATUS_FUNCTIONLINK_CASH_ITEM,
};

// 염색

#define DYEING_ITEM_MAX				(4)			// 염색 최대 갯수

#define DYEING_ITEM_COLOR_NUM_MAX	(36)
#define DYEING_BODY_COLOR_NUM_MAX	(255)

enum
{
	DYEING_TYPE_HAIR,
	DYEING_TYPE_HEAD,
	DYEING_TYPE_UPCLOTHES,
	DYEING_TYPE_SKIN,
	DYEING_TYPE_MAX,
};

enum DEAD_STATE_
{
	DEAD_STATE_NONE = 0,
	DEAD_STATE_UNDEAD,		// 변이
	DEAD_STATE_VANISH,		// 사라짐
	DEAD_STATE_OPEN_GATE,	// 공성전용 (현재 사용 안함)
	DEAD_STATE_BY_PK,		// pk로 죽었음
};


enum PortalError
{
	PORTAL_NO_ERROR,
	PORTAL_SELECT_DIFFICULTY,

	PORTAL_INVALID_MAP_PORTAL_INDEX,
	PORTAL_TOO_FAR_MAP_PORTAL,
	PORTAL_NOT_FOUND_NPC,
	PORTAL_NOT_PORTAL_NPC,
	PORTAL_TOO_FAR_NPC,
	PORTAL_NOT_FOUND_PORTAL_ID,
	PORTAL_NOT_OPEN_MAP,

	PORTAL_FAILED_LEVEL,
	PORTAL_FAILED_COIN,
	PORTAL_FAILED_FAME,
	PORTAL_FAILED_ITEM,
	PORTAL_FAILED_JOB,
	PORTAL_FAILED_QUEST,
	PORTAL_FAILED_QUEST_MISSION,
	PORTAL_FAILED_COMPLETED_QUEST,

	PORTAL_INVALID_DIFFICULTY,

	PORTAL_FAILED_PENDING_ITEM_ACTION,				// 아이템 관련 행동 불가
	PORTAL_FAILED_WORLD_EVENT,
	PORTAL_FAILED_USER_FULL,
	PORTAL_FAILED_TOWER_LEVEL,		// 달의 탑 레벨 제한
	PORTAL_FAILED_BIND_TOWER,		// 달의 탑 이미 입장했음
	PORTAL_FAILED_NOT_HAVE_TOWER_ENTER_ITEM,	// 달의 탑 입장 아이템 없음
	PORTAL_FAILED_TOWER_NOT_PARTY_MASTER,		// 사신도 - 파티장이 아님
	PORTAL_FAILED_TOWER_MEMBER_DIFF_MAP,		// 사신도 - 파티원이 다른 맵에 있음
	PORTAL_FAILED_TOWER_MEMBER_LOADING,			// 사신도 - 파티원이 맵 입장 중임
	PORTAL_FAILED_TOWER_MEBER_ERROR,			// 사신도 - 파티원이 입장 불가능 함
	PORTAL_FAILED_INSTANCE_COOLTIME,			// 던전 쿨타임
};

enum RescueError
{
	RESCUE_NO_ERROR,
	RESCUE_NOT_FOUND_NPC,
	RESCUE_ALREADY_RESCUED_NPC,
};


enum RickshawError
{
	RICKSHAW_ERROR_SUCCESS = 0,
	RICKSHAW_ERROR_NOT_FOUND_SCRIPT,
	RICKSHAW_ERROR_TOO_FAR_DISTANCE,
	RICKSHAW_ERROR_NOT_ENOUGH_COIN,
	RICKSHAW_ERROR_NOT_RICHSHAW_NPC,
	RICKSHAW_ERROR_NOT_HAVE_QUEST,
	RICKSHAW_ERROR_RELEASE_PET_ERROR,
};

enum ReviveError
{
	REVIVE_ERR_NOT_ERROR,						// 에러 아님
	REVIVE_ERR_NOT_DEAD,						// 죽은 상태가 아님
	REVIVE_ERR_TOO_LOW_REVIVE_END_TIME,			// 부활 대기 시간이 남았음
	REVIVE_ERR_INVALID_STATE,					// 잘못된 STATE 값
	REVIVE_ERR_CASH_REVIVE_LEVEL_LIMIT,			// 케쉬로 부활할수 있는 레벨이 아님
	REVIVE_ERR_NOT_ENOUGHT_CASH,				// 케쉬가 모자름
	REVIVE_ERR_NOT_ENOUGHT_COIN,				// 코인이 모자름
	REVIVE_ERR_NO_ACTION_BILLING_SERVER,		// 빌링 서버가 정상작동하지 않음
	REVIVE_ERR_NOT_CASH_REVIVE_USE_STATE_ERROR,	// 케쉬 부활 사용 상태 오류
	REVIVE_ERR_NOT_ITEM_SCRIPT,					// 아이템 없음
	REVIVE_ERR_ITEM_SORT_ERROR,					// 부활사용 아이템 아님(소트에러)
	REVIVE_ERR_LIMIT_CURRENT_POSITION,			// 제자리 부활 제한
	REVIVE_ERR_PENDING_ITEM_ACTION,				// 아이템 관련 행동 불가
};

enum ChannelUniqueMobError
{
	CHANNEL_UNIQUE_MOB_NO_ERROR,
	CHANNEL_UNIQUE_MOB_NOT_FOUND_MAP,
	CHANNEL_UNIQUE_MOB_NOT_FOUND_SCRIPT,
	CHANNEL_UNIQUE_MOB_WORLD_EVENT,
	CHANNEL_UNIQUE_MOB_ALREADY_RESPAWN,
	CHANNEL_UNIQUE_MOB_CREATE_FAIL,
};

enum BuyAffectErrors
{
	BUY_AFFECT_NO_ERROR,
	BUY_AFFECT_NOT_FOUND_NPC,
	BUY_AFFECT_INVALID_SALE_ID,
	BUY_AFFECT_NOT_ENOUGH_COIN,
};

enum EventPollError
{
	EVENT_POLL_SUCCESS,				// 성공
	EVENT_POLL_DB_ERROR,			// db 에러
	EVENT_POLL_ALREADY_VOTE,		// 투표 했음
	EVENT_POLL_NOT_VOTE,			// 투표 안했음
	EVENT_POLL_CHOISE_ERROR,		// 선택 에러 (1~5 외 다른 번호 선택)
};

enum ChangeActorNameError
{
	CHANGE_ACTOR_NAME_SUCCESS,
	CHANGE_ACTOR_NAME_NOT_FOUND_ITEM,	// 이름 변경 아이템 아님
	CHANGE_ACTOR_NAME_NOT_FOUND_USER,	// 유저 입장 상태가 아님
	CHANGE_ACTOR_NAME_INVALID_NAME,		// 사용할 수 없는 이름
	CHANGE_ACTOR_NAME_DUP_NAME,			// 중복된 이름
	CHANGE_ACTOR_NAME_DB_ERROR,			// DB 오류
};

enum CustomizeCharError
{
	CUSTOMIZE_CHAR_SUCCESS,
	CUSTOMIZE_CHAR_NOT_FOUND_ITEM,		// 아이템 없음
	CUSTOMIZE_CHAR_TYPE_ERROR,			// 얼굴, 몸통만 변경 가능
	CUSTOMIZE_CHAR_ITEM_SORT_ERROR,		// 아이템 종류 틀림
};

enum GrowthWeaponError
{
	GROWTH_WEAPON_SUCCESS,				// 성공
	GROWTH_WEAPON_FAIL,					// 실패
	GROWTH_WEAPON_NOT_FOUND_ITEM,		// 아이템 없음
	GROWTH_WEAPON_NOT_FOUND_SCRIPT,		// 스크립트 없음
	GROWTH_WEAPON_RANK_LIMIT,			// 최대 랭크
	GROWTH_WEAPON_NOT_ENOUGH_EXP,		// 경험치 부족
	GROWTH_WEAPON_NOT_FOUND_NEED_ITEM,	// 재료 아이템 없음
	GROWTH_WEAPON_INVALID_DISSEMBLE,	// 분해 불가
	GROWTH_WEAPON_DISSEMBLE_EQUIPMENT_ERROR,	// 분해 장비 타입 오류
	GROWTH_WEAPON_INVALID_MIXING,		// 조합 불가
	GROWTH_WEAPON_MIXING_COUNT_ERROR,	// 조합 갯수 오류
	GROWTH_WEAPON_MIXING_NOT_ENOUGH_NEED_ITEM,	// 조합 아이템 부족
	GROWTH_WEAPON_NPC_MIXING_ITEM_ERROR,	// npc 조합 아이템 오류
	GROWTH_WEAPON_INVENTORY_FULL,		// 가방 풀
	GROWTH_WEAPON_NOT_FOUND_NPC,		// npc 없음
	GROWTH_WEAPON_TOO_FAR_NPC,			// npc 멀리 있음
};
