#pragma once

enum DATABASE_FLAG_
{
	DATABASE_FLAG_SELECT = 0,			// SELECT
	DATABASE_FLAG_COMMAND			// INSERT, UPDATE, DELETE
};

#define QUERY_STRING_MAX		(1024)

#define ON_DB_ERROR_STOP			0
#define ON_DB_ERROR_CONTINUE		1
